### ISSUE TITLE
Cant use the EpanetSimulator  after error: 302 occurs

### ISSUE THREAD

**Issue by Tabznator** [USEPA/WNTR#53] opened 2018-08-09 18:23 UTC
Hello, 

I am trying to run multiple simulations using the EpanetSimulator but some of the networks I am working on  produce the following error: ERROR:wntr.epanet.toolkit: EPANET error: 302.

The problem is that once this error occurs I am unable to continue using the EpanetSimulator unless I reset the whole script. I was wondering if there is a work around this.

**Comment by michaelbynum** [comment] 2018-08-09 19:40
Can you share a simple script that recreates the error? What operating system are you using?

Michael

On Aug 9, 2018, at 12:23 PM, Tabznator <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello,

I am trying to run multiple simulations using the EpanetSimulator but some of the networks I am working on produce the following error: ERROR:wntr.epanet.toolkit: EPANET error: 302.

The problem is that once this error occurs I am unable to continue using the EpanetSimulator unless I reset the whole script. I was wondering if there is a work around this.

**Comment by Tabznator** [comment] 2018-08-09 20:37
Here is a sample code and i am using windows 7. The code runs perfectly for about half of the pipes so am not sure about what triggers the error. 
def get_error_list():
    wnt = wntr.network.WaterNetworkModel(inp_file)
    error_box,source_pipes = [],[]
    pipes = wnt.link_name_list
    sources = wnt.tank_name_list
    sources.extend(wnt.reservoir_name_list)
    
    if sources == []:
        raise no_sources   
    source_pipes = [link for source in sources for link in wnt.get_links_for_node(str(source)) ]
    
    for pipe in pipes:
        wnt = wntr.network.WaterNetworkModel(inp_file)
        
        if pipe not in source_pipes:
            
            try:
                wnt.remove_link(pipe)
                sim = wntr.sim.EpanetSimulator(wnt)     
                results = sim.run_sim()
                
               
            except Exception,e:  
                error_box.append(pipe)
                
    return error_box,source_pipes

**Comment by michaelbynum** [comment] 2018-08-13 17:07
@dbhart Any thoughts? This seems odd to me.

**Comment by michaelbynum** [comment] 2018-08-14 15:08
@Tabznator We are having difficult reproducing the error. Do you have the same problem with any of the example networks distributed with WNTR?

**Comment by kaklise** [comment] 2020-11-04 19:13
While we were not able to reproduce this error, we suspect that the issue has been resolved with the use of EPANET 2.2 in WNTR.  If this is not the case, the issue can be reopened.

**Closed by kaklise** 2020-11-04 19:13 UTC
