### ISSUE TITLE
Possible D-W friction factor error?

### ISSUE THREAD

**Issue by GeertD** [USEPA/WNTR#243] opened 2021-11-29 14:17 UTC
Hi,

Using Darcy-Weisbach hydraulics:
It looks like the calculated pipe friction factor (and pipe headloss) in WNTR differs from Epanet 2.2 calculations and my own calculations.

The differences are getting larger with lower velocity (Reynolds) and larger pipe roughness. **Up to about 30% difference, considerable.**

Please could you check for possible error?

Settings:
Tested WNTR on Google Colab: headloss = "D-W", simulator = EpanetSimulator, other details see pdf attached.
Checked against Epanet 2.2 (windows app) with same system settings, and also against own excel spreadsheet (Darcy-weisbach friction losses).

Results:
friction factors: WNTR / Epanet 2.2 / own calcs : system details
test1:
**0.034 / 0.0475** / 0.0474
system:  medium (flowrate 10 m3/h, density = 0.998, visc = 1.022), pipe (50 m, 120 mm diam, roughn = 2 mm, minor_losses = 0) ; 30% lower friction compared to Epanet (and own calc.)

test2:
0.0147 /  0.0152  /  0.0151
system:  medium (flowrate 100 m3/h, density = 0.998, visc = 1.022), pipe (50 m, 120 mm diam, roughn = 0.007 mm, minor_losses = 0) ; fairly close to Epanet

[Test_OnePipe.ipynb - Colaboratory.pdf](https://github.com/USEPA/WNTR/files/7618640/Test_OnePipe.ipynb.-.Colaboratory.pdf)

**Comment by kaklise** [comment] 2021-11-30 19:26
Some of the pipe attributes are cut off in the PDF, so I'm not sure if I replicated your example correctly.  Using some assumed pipe attributes, the EpanetSimulator in WNTR and the EPANET 2.2 GUI produce the equal friction factors.  Can you recreate the PDF or post the INP file so I can recheck?

**Comment by GeertD** [comment] 2021-12-03 12:28
Hi, 
please find the jupyter notebook attached.

I ran this in Google Colab, and that gave the results above.
Just tested it again and same results.


[Test_OnePipe.zip](https://github.com/USEPA/WNTR/files/7649543/Test_OnePipe.zip)

**Comment by kaklise** [comment] 2022-06-01 19:08
Sorry for the delay on this.  When I ran the notebook, I get 0.034 for the friction factor of P1.  I get the same result when I load the INP file into the EPANET 2.2 GUI.

**Comment by kaklise** [comment] 2023-01-17 17:33
I am closing this issue as I'm not able to reproduce the values.  Please reopen if this is still an issue.

**Closed by kaklise** 2023-01-17 17:33 UTC

**Comment by GeertD** [comment] 2023-01-17 20:04
Hi Katherine,

That's fine.
Thanks for looking into it.

Regards,

Geert
