### ISSUE TITLE
Simulation did not converge. Jacobian is singular at iteration 0

### ISSUE THREAD

**Issue by Mottabata** [USEPA/WNTR#217] opened 2021-06-29 17:08 UTC
Hi,

I was trying to run your earthquake example on my WDN and at step 8 of simulating hydraulics without repair (and assigning leak model) the simulation did not converge and jacobian was singular at iteration 0. i am running the simulation using WNTRSimulator and "PDD" analysis. Could you please help addressing this.

Note: i read your previous post about solving it by switching nominal and minimum pressure to 1 and 0 and still did show the same simulation error.

Thanks,
MB

**Comment by kaklise** [comment] 2021-06-29 22:27
I just ran the Earthquake example using the current version of WNTR and did not see that error.  This uses the WNTRSimulator with PDD.  We generally get the error you mentioned when there are sections of the network not connected to a source (tank or reservoir).  Did you change anything in the analysis that might cause that to occur?  We have an open PR with a solution to this issue, but it is currently not scaling to large networks.

**Comment by Mottabata** [comment] 2021-06-30 16:47
I ran it on NET3 and had no issues but when I ran it on my network this happened. Here I attach the INP of my network if you could look at it.

**Comment by kaklise** [comment] 2021-07-07 19:55
I am able to reproduce this error, but I don't think the Earthquake demo is the issue.  If I run the demo with the INP file provided, the epicenter is far enough away that the network is not damaged.

This issue is related to #187. The WNTRSimulator is not able to handle nodes that become isolated.  There is a patch provided in PR #206, but this requires further testing and we found that the solution is not scalable to large networks.  We'll try to get that wrapped up soon.

I plan to close this issue and keep #187 open.

**Comment by Mottabata** [comment] 2021-07-07 20:38
I tried it with an epicenter close to the WTP at (367242, 4656005) and other close by epicenters and I still had the same issue.
[cid:7035dfdd-aa84-4038-ad81-41b56be73c6c]
________________________________

**Comment by kaklise** [comment] 2021-07-07 20:41
Thanks for clarifying.  Since we get the error even without added damage, I think we're still seeing the same issue as before.

**Closed** 2021-07-08 18:31 UTC
